name = "p2pagos-website"
compatibility_date = "2025-01-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "p2pagos-website-content"
database_id = "REPLACE_WITH_D1_DATABASE_ID"
